### ISSUE TITLE
Bug in Celsius to Kelvin and Rankine conversion

### ISSUE THREAD

**Issue by rafasilveira** [viunow/tempconversorWeb#2]
Hello! 
Nice work ;)
I've found a small bug while trying to convert from Celsius to Kelvin. Seems to be a typo [here](https://github.com/viunow/tcw/blob/726d63b46b0d13bc2e94fede446dc947c8bfc14b/conversor.js#L21).

**Input:**
Celsius
20

**Expected output:**
Kelvin: 293.15 K
Rankine: 527.67 ºRa

**Actual output:**
Kelvin: 527.67 ºRa
Rankine: 20273.15 K

**Evidence:**
![Screen Shot 2021-01-30 at 10 14 14](https://user-images.githubusercontent.com/64478636/106357369-76323700-62e4-11eb-856b-fa69ff506414.png)

**Comment by viunow** [comment]
Seems like the error was caused because valNum aren't have the parseInt, I change the code and tested the outputs, it works! 
Solution: `valNum = parseInt(valNum);`
